namespace Kairon.Backend.Models.Platform;

/// <summary>
/// A long-lived, revocable per-project credential. Only KeyPrefix (first 12 chars, for lookup)
/// and a SHA-256 hash of the full key are ever stored - the raw key is returned once, at
/// creation/redemption, and never again. Ported from Azzy's productization branch.
/// </summary>
public sealed class ProjectApiCredential
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid ProjectId { get; set; }
    public string Name { get; set; } = string.Empty;
    public string KeyPrefix { get; set; } = string.Empty;
    public string KeyHash { get; set; } = string.Empty;
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? RevokedAt { get; set; }

    /// <summary>EF concurrency token (AppDbContext) - regenerated by SdkPairingService.
    /// CompleteRepairAsync whenever it revokes this credential as the old side of a re-pair
    /// completion. This is what makes two CONFIRMED sessions racing to replace the exact same old
    /// credential resolve to exactly one winner: both can read RevokedAt as still-null before
    /// either commits, but only the first to actually commit can succeed - the second's write is
    /// conditioned on the RowVersion it originally read, which the database no longer matches, so
    /// EF surfaces a DbUpdateConcurrencyException instead of silently overwriting. Not yet bumped
    /// by every other mutator of this entity (e.g. ProjectCredentialService.RevokeAsync, an
    /// operator-driven manual revoke) - that is a different, non-racing code path.</summary>
    public Guid RowVersion { get; set; } = Guid.NewGuid();
}
