// <auto-generated />
using System;
using AIDIP.Backend.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIDIP.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AIDIP.Backend.Models.Analysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutputJson")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Score")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ProjectId", "Type");

                    b.ToTable("Analyses");
                });

            modelBuilder.Entity("AIDIP.Backend.Models.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Application")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ErrorType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Resolved")
                        .HasColumnType("bit");

                    b.Property<string>("Service")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SreIncidentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StackTrace")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint");

                    b.HasIndex("Environment");

                    b.HasIndex("SreIncidentId");

                    b.HasIndex("StatusCode");

                    b.HasIndex("ProjectId", "Timestamp");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("AIDIP.Backend.Models.Machine", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<string>("AgentCredentialHash").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
                    b.Property<string>("AgentVersion").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<string>("Architecture").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<string>("HostName").IsRequired().HasMaxLength(255).HasColumnType("nvarchar(255)");
                    b.Property<DateTime>("LastSeenAt").HasColumnType("datetime2");
                    b.Property<string>("OperatingSystem").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                    b.Property<DateTime>("RegisteredAt").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("LastSeenAt");
                    b.ToTable("Machines");
                });

            modelBuilder.Entity("AIDIP.Backend.Models.DiscoveredApplication", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<double>("CpuPercent").HasColumnType("float");
                    b.Property<string>("Executable").IsRequired().HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                    b.Property<DateTime>("FirstSeenAt").HasColumnType("datetime2");
                    b.Property<bool>("IsRunning").HasColumnType("bit");
                    b.Property<DateTime>("LastSeenAt").HasColumnType("datetime2");
                    b.Property<Guid>("MachineId").HasColumnType("uniqueidentifier");
                    b.Property<long>("MemoryBytes").HasColumnType("bigint");
                    b.Property<string>("Name").IsRequired().HasMaxLength(255).HasColumnType("nvarchar(255)");
                    b.Property<int>("ProcessId").HasColumnType("int");
                    b.Property<DateTime>("ProcessStartedAt").HasColumnType("datetime2");
                    b.Property<string>("Runtime").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.HasKey("Id");
                    b.HasIndex("MachineId", "IsRunning");
                    b.HasIndex("MachineId", "ProcessId", "ProcessStartedAt").IsUnique();
                    b.ToTable("DiscoveredApplications");
                });

            modelBuilder.Entity("AIDIP.Backend.Models.Metric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Application")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Component")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double?>("CpuPercent")
                        .HasColumnType("float");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("ErrorCount")
                        .HasColumnType("bigint");

                    b.Property<double?>("MemoryPercent")
                        .HasColumnType("float");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("QueueDepth")
                        .HasColumnType("bigint");

                    b.Property<long>("RequestCount")
                        .HasColumnType("bigint");

                    b.Property<double?>("ResponseTimeMs")
                        .HasColumnType("float");

                    b.Property<long?>("RetryCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Service")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Environment");

                    b.HasIndex("ProjectId", "Timestamp");

                    b.ToTable("Metrics");
                });

            modelBuilder.Entity("AIDIP.Backend.Models.KaironProject", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<string>("Slug").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.HasKey("Id");
                    b.HasIndex("Slug").IsUnique();
                    b.ToTable("Projects");
                });

            modelBuilder.Entity("AIDIP.Backend.Models.KaironEnvironment", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<Guid>("ProjectId").HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("ProjectId", "Name").IsUnique();
                    b.ToTable("Environments");
                });

            modelBuilder.Entity("AIDIP.Backend.Models.MonitoredApplication", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<DateTime?>("LastTelemetryAt").HasColumnType("datetime2");
                    b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<Guid>("ProjectId").HasColumnType("uniqueidentifier");
                    b.Property<string>("Runtime").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<string>("Service").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.HasKey("Id");
                    b.HasIndex("ProjectId", "Service").IsUnique();
                    b.ToTable("MonitoredApplications");
                });

            modelBuilder.Entity("AIDIP.Backend.Models.TelemetrySourceRegistration", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<Guid?>("ApplicationId").HasColumnType("uniqueidentifier");
                    b.Property<string>("InstallationId").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<DateTime>("LastSeenAt").HasColumnType("datetime2");
                    b.Property<Guid>("ProjectId").HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("RegisteredAt").HasColumnType("datetime2");
                    b.Property<string>("SourceType").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<string>("Version").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.HasKey("Id");
                    b.HasIndex("ApplicationId");
                    b.HasIndex("LastSeenAt");
                    b.HasIndex("ProjectId", "InstallationId").IsUnique();
                    b.ToTable("TelemetrySources");
                });

            modelBuilder.Entity("AIDIP.Backend.Models.TelemetryReceipt", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<string>("Application").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<string>("Environment").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<Guid>("EventId").HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("EventTimestamp").HasColumnType("datetime2");
                    b.Property<string>("EventType").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<string>("PayloadJson").IsRequired().HasMaxLength(16000).HasColumnType("nvarchar(max)");
                    b.Property<Guid>("ProjectId").HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("ReceivedAt").HasColumnType("datetime2");
                    b.Property<string>("Service").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<string>("Severity").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                    b.Property<string>("Source").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<Guid?>("SourceId").HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("EventId").IsUnique();
                    b.HasIndex("ProjectId", "ReceivedAt");
                    b.ToTable("TelemetryReceipts");
                });

            modelBuilder.Entity("AIDIP.Backend.Models.ProjectApiCredential", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("KeyHash").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
                    b.Property<string>("KeyPrefix").IsRequired().HasMaxLength(16).HasColumnType("nvarchar(16)");
                    b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<Guid>("ProjectId").HasColumnType("uniqueidentifier");
                    b.Property<DateTime?>("RevokedAt").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("ProjectId", "KeyPrefix");
                    b.ToTable("ProjectApiCredentials");
                });

            modelBuilder.Entity("AIDIP.Backend.Models.PlatformAuditEvent", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<string>("Action").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<string>("Actor").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<string>("Category").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<string>("DataJson").HasMaxLength(8000).HasColumnType("nvarchar(max)");
                    b.Property<string>("Message").HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                    b.Property<Guid?>("ProjectId").HasColumnType("uniqueidentifier");
                    b.Property<string>("Result").IsRequired().HasMaxLength(40).HasColumnType("nvarchar(40)");
                    b.Property<string>("TargetId").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<string>("TargetType").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<DateTime>("Timestamp").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("Timestamp");
                    b.HasIndex("ProjectId", "Timestamp");
                    b.ToTable("PlatformAuditEvents");
                });

            modelBuilder.Entity("AIDIP.Backend.Models.SdkPairingSession", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<Guid>("ApplicationId").HasColumnType("uniqueidentifier");
                    b.Property<string>("CodeHash").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<DateTime>("ExpiresAt").HasColumnType("datetime2");
                    b.Property<Guid>("ProjectId").HasColumnType("uniqueidentifier");
                    b.Property<DateTime?>("RedeemedAt").HasColumnType("datetime2");
                    b.Property<DateTime?>("RevokedAt").HasColumnType("datetime2");
                    b.Property<string>("SdkType").IsRequired().HasMaxLength(30).HasColumnType("nvarchar(30)");
                    b.HasKey("Id");
                    b.HasIndex("CodeHash").IsUnique();
                    b.HasIndex("ApplicationId", "ExpiresAt");
                    b.ToTable("SdkPairingSessions");
                });

            modelBuilder.Entity("AIDIP.Backend.Models.SdkInstallation", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<Guid>("ApplicationId").HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("InstallationId").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<string>("KeyHash").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
                    b.Property<string>("KeyPrefix").IsRequired().HasMaxLength(16).HasColumnType("nvarchar(16)");
                    b.Property<DateTime?>("LastSeenAt").HasColumnType("datetime2");
                    b.Property<Guid>("ProjectId").HasColumnType("uniqueidentifier");
                    b.Property<DateTime?>("RevokedAt").HasColumnType("datetime2");
                    b.Property<string>("SdkType").IsRequired().HasMaxLength(30).HasColumnType("nvarchar(30)");
                    b.Property<Guid>("SourceId").HasColumnType("uniqueidentifier");
                    b.Property<string>("Version").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.HasKey("Id");
                    b.HasIndex("InstallationId").IsUnique();
                    b.HasIndex("ProjectId", "KeyPrefix");
                    b.ToTable("SdkInstallations");
                });

            modelBuilder.Entity("AIDIP.Backend.Models.Sre.IncidentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DataJson")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("NewState")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PreviousState")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Result")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId", "Timestamp");

                    b.ToTable("IncidentEvents");
                });

            modelBuilder.Entity("AIDIP.Backend.Models.DiscoveredApplication", b =>
                {
                    b.HasOne("AIDIP.Backend.Models.Machine", "Machine")
                        .WithMany("Applications").HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Machine");
                });

            modelBuilder.Entity("AIDIP.Backend.Models.Machine", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("AIDIP.Backend.Models.KaironEnvironment", b =>
                {
                    b.HasOne("AIDIP.Backend.Models.KaironProject", "Project")
                        .WithMany("Environments").HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Project");
                });

            modelBuilder.Entity("AIDIP.Backend.Models.MonitoredApplication", b =>
                {
                    b.HasOne("AIDIP.Backend.Models.KaironProject", "Project")
                        .WithMany("Applications").HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Project");
                });

            modelBuilder.Entity("AIDIP.Backend.Models.TelemetrySourceRegistration", b =>
                {
                    b.HasOne("AIDIP.Backend.Models.MonitoredApplication", "Application")
                        .WithMany("TelemetrySources").HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.SetNull);
                    b.Navigation("Application");
                });

            modelBuilder.Entity("AIDIP.Backend.Models.ProjectApiCredential", b =>
                {
                    b.HasOne("AIDIP.Backend.Models.KaironProject", "Project")
                        .WithMany("Credentials").HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Project");
                });

            modelBuilder.Entity("AIDIP.Backend.Models.KaironProject", b =>
                {
                    b.Navigation("Applications");
                    b.Navigation("Credentials");
                    b.Navigation("Environments");
                });

            modelBuilder.Entity("AIDIP.Backend.Models.MonitoredApplication", b =>
                {
                    b.Navigation("TelemetrySources");
                });

            modelBuilder.Entity("AIDIP.Backend.Models.Sre.IncidentEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ItemCount")
                        .HasColumnType("int");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId", "Kind");

                    b.ToTable("IncidentEvidence");
                });

            modelBuilder.Entity("AIDIP.Backend.Models.Sre.RemediationAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExecutionError")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ExecutionResult")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ExpectedOutcome")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("PolicyDecision")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("bit");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid?>("VerificationResultId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ActionKey")
                        .IsUnique();

                    b.HasIndex("IncidentId", "Status");

                    b.ToTable("RemediationActions");
                });

            modelBuilder.Entity("AIDIP.Backend.Models.Sre.SreIncident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AffectedComponent")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("AffectedEndpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double?>("Confidence")
                        .HasColumnType("float");

                    b.Property<string>("ContributingFactorsJson")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrelatedMetricsJson")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrelationKey")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DiagnosisStale")
                        .HasColumnType("bit");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("IncidentKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PredictedImpact")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("PredictedRisk")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RecommendationsJson")
                        .HasMaxLength(16000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RemediationState")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RootCause")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SignalCount")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Summary")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("SymptomsJson")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelemetryReferencesJson")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerificationState")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationKey");

                    b.HasIndex("IncidentKey")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("Environment", "Service");

                    b.HasIndex("ProjectId", "Timestamp");

                    b.ToTable("SreIncidents");
                });

            modelBuilder.Entity("AIDIP.Backend.Models.Sre.VerificationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComparisonsJson")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("RecoveryScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId", "StartedAt");

                    b.ToTable("VerificationResults");
                });

            modelBuilder.Entity("AIDIP.Backend.Models.Sre.IncidentEvent", b =>
                {
                    b.HasOne("AIDIP.Backend.Models.Sre.SreIncident", "Incident")
                        .WithMany("Events")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("AIDIP.Backend.Models.Sre.IncidentEvidence", b =>
                {
                    b.HasOne("AIDIP.Backend.Models.Sre.SreIncident", "Incident")
                        .WithMany("Evidence")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("AIDIP.Backend.Models.Sre.RemediationAction", b =>
                {
                    b.HasOne("AIDIP.Backend.Models.Sre.SreIncident", "Incident")
                        .WithMany("Actions")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("AIDIP.Backend.Models.Sre.VerificationResult", b =>
                {
                    b.HasOne("AIDIP.Backend.Models.Sre.SreIncident", "Incident")
                        .WithMany("Verifications")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("AIDIP.Backend.Models.Sre.SreIncident", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Events");

                    b.Navigation("Evidence");

                    b.Navigation("Verifications");
                });
#pragma warning restore 612, 618
        }
    }
}
